### ISSUE TITLE
Warning! Unlikely big volume range (=10240), cval->res is probably wrong

### ISSUE THREAD

**Issue by topherbuckley** [xanderhendriks/nsrt-mk3-dev#1]
When trying to find the device via `dmesg | grep -i usb` as instructed in the README I see a curious warning alongside the device info:

>[151140.895498] usb 3-1: Warning! Unlikely big volume range (=10240), cval->res is probably wrong.

Are you familiar with this warning? 

Also, thanks for this repo, it has definitely saved me a lot of time trying to implement all the serial code from the datasheet!

**Comment by xanderhendriks** [comment]
Sorry for the delay. I got the message while I was travelling and afterwards it took some time before I had the device connected to a linux system again. With the device connected to a Raspberry Pi here I see the same error, but I don't see any impact to the functionality. I'll check with Convergence Instruments if they have an explanation for this and to understand if this is a reason for concern.

**Comment by BPaillard** [comment]
Hi Topher, Xander

The warning that Linux is sending is related to the maximum volume value of +40 dB that the NSRT_mk3_Dev is reporting in response to the Get Max request that Linux is sending to the volume control. Decimal 10240 represents +40 dB.
I am not sure why Linux is alarmed by that value. +40 dB is well within the values allowed by the Audio Class 1.0 for a volume control. It may just be that this is "unusual" for a typical USB microphone. But in the case of the NSRT_mk3 series, the volume limits are related to the scale factor when converting from the integer format to a pressure value in Pascal.
For the float format, the volume control has not effect at all and is just there as a placeholder, to prevent some OSes from complaining (or refusing to enumerate the Audio Interface altogether).
I hope this helps

Bruno

**Comment by BPaillard** [comment]
Topher, Xander

One more note to clarify:

The value 10240 represents +40 dB, because the volume resolution is defined and reported as 0.0039 dB. Internally the NSRT_mk3 series uses a floating point unit to do scaling and conversion, so such a fine-grained resolution on the volume control is not a problem. But it may be that Linux is not "seeing" the reported resolution value, and assuming something larger, such as 1 dB/step or more, hence the warning...?

**Comment by topherbuckley** [comment]
Thanks for extrapolating on all of this. So long as it doesn't alarm either of you, I'm not worried for now. Happy to have this info on paper in case I need to reference it later though. Cheers!
